TRADES = [
    "Main Material",
    "Temporary Works",
    "Reinforced Concrete",
    "Steel Structure",
    "Wet Waterproofing",
    "Tile / Stone Works",
    "Painting Works",
    "Finishing Carpentry",
    "Metal Works",
    "Windows & Curtain Wall",
    "Furniture",
    "Interior Works",
    "Pile / Earthworks",
    "External Works",
    "Equipment",
    "Façade",
    "DAEIL",
    "TAESUNG",
    "AVANCE",
    "KBSL",
    "MIT",
    "Siemens - Electrical",
    "DIMO",
    "Other Electrical Works",
    "MUKYUNG",
    "YOONCHANG",
    "DAEJUNG",
    "TROX",
    "BD123 - Mechanical",
    "Sanitary Works",
    "Siemens - Mechanical",
    "Other Architectural Works",
]
